bonds/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy

from django.contrib.auth.decorators import login_required

from . import views

app_name = 'bonds'

urlpatterns = [
    url(r'bond/add/$', login_required(views.BondCreate.as_view(success_url=reverse_lazy('bonds:bond_add'))), name='bond_add'),
]

bondtracker/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from reports.views import allTransactions

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', allTransactions),
    url(r'^bonds/', include('bonds.urls')),
    url(r'^transactions/', include('transactions.urls')),
    url(r'^reports/', include('reports.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reports/urls.py
from django.conf.urls import url

from . import views

app_name = 'reports'

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.allTransactions, name='index'),
    url(r'^brokers/$', views.brokers, name='brokers'),
    url(r'^bondtypes/$', views.bondtypes, name='bondtypes'),
    url(r'^bonds/$', views.bonds, name='bonds'),
    url(r'^by-broker/(?P<broker_id>[0-9]+)/$', views.byBroker, name='by-broker'),
    url(r'^by-bondtype/(?P<bondtype_id>[0-9]+)/$', views.byBondType, name='by-bond-type'),
    url(r'^by-bond/(?P<bond_id>[0-9]+)/$', views.byBond, name='by-bond'),
    url(r'^changeDates/$', views.changeDates, name="changeDates"),
    url(r'^resetDates/$', views.resetDates, name="resetDates"),
    url(r'^all-transactions/$', views.allTransactions, name="all-transactions"),
    url(r'^aggregate/all/$', views.aggregateAll, name="aggregateAll"),
    url(r'^aggregate/by-broker/$', views.aggregateByBroker, name="aggregateByBroker"),
    url(r'^aggregate/by-bondtype/$', views.aggregateByBondType, name="aggregateByBondType"),
]

bonds/models.py
from django.db import models

class BondType(models.Model):
    """A type of bond, independent of maturity"""
    name = models.CharField(max_length=80)  # NTN-B Principal
    code = models.CharField(max_length=20)
    prefixed = models.BooleanField()
    hasCoupon = models.BooleanField()

    def __str__(self):
        return "{} ({})".format(self.code, self.name)

    class Meta:
        ordering = ['code']
    
class Bond(models.Model):
    bondtype = models.ForeignKey(BondType, on_delete=models.SET_NULL, null=True)
    maturity = models.DateField()
    latestPrice = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    latestPriceDate = models.DateField(blank=True, null=True)

    def __str__(self):
        price = ""
        priceDate = ""
        if self.latestPrice is not None:
            price = " <R$ " + str(self.latestPrice) + ">"
            priceDate = self.latestPriceDate.strftime("%d/%m/%y")
            
        return str(self.bondtype.code) + " " + str(self.maturity.strftime("%Y")) + price + " " + priceDate

    class Meta:
        ordering = ['bondtype', 'maturity']

reports/models.py
from django.db import models

# Create your models here.

bonds/forms.py
from django.forms import ModelForm
from django.contrib.admin import widgets

from .models import Bond

class BondForm(ModelForm):
    class Meta:
        model = Bond
        fields = ['bondtype', 'maturity']

    def __init__(self, *args, **kwargs):
        super(BondForm, self).__init__(*args, **kwargs)
        self.fields['maturity'].widget = widgets.AdminDateWidget()
        # self.fields['latestPriceDate'].widget = widgets.AdminDateWidget()

bonds/views.py
from django.views.generic.edit import CreateView

from django.shortcuts import render

from .models import Bond
from .forms import BondForm

class BondCreate(CreateView):
    model = Bond
    form_class = BondForm

reports/views.py
from collections import namedtuple, defaultdict

from django.shortcuts import render, get_object_or_404, redirect
from django.utils.http import is_safe_url
from django.urls import reverse

from transactions.models import Broker, Transaction, Investor
from bonds.models import BondType, Bond
from .calculator import transactions_total, aggregateTransactions, BrokerBonds, BondTypeBonds, addAnnualizedRates
from .util import parseDate, parseFromDate, parseToDate, displayDate
from .util import DEFAULT_FROM_DATE, DEFAULT_TO_DATE

def index(request):
    return render(request, 'reports/index.html')

# Produce lists of entities
def brokers(request):
    investor = Investor.objects.get(user=request.user)
    brokers = Broker.objects.filter(client=investor)
    return render(request, 'reports/brokers.html', {'brokers': brokers})

def bondtypes(request):
    bondtypes = BondType.objects.all()
    return render(request, 'reports/bondtypes.html', {'bondtypes': bondtypes})

def bonds(request):
    bonds = Bond.objects.all()
    return render(request, 'reports/bonds.html', {'bonds': bonds})

# Retrieve transactions
CommonTransactionData = namedtuple("CommonTransactionData",
                                   ["investor", "from_date", "to_date"])

def get_common_data(request):
    return CommonTransactionData(Investor.objects.get(user=request.user),
                                 parseFromDate(request),
                                 parseToDate(request))

def byBroker(request, broker_id):
    broker = get_object_or_404(Broker, pk=broker_id)

    common = get_common_data(request)
                                   
    transactions = Transaction.objects.filter(
        broker=broker,
        owner=common.investor,
        transactionDate__gte=common.from_date,
        transactionDate__lte=common.to_date)
    
    total = transactions_total(transactions)

    addAnnualizedRates(transactions)

    return render(request, 'reports/byBroker.html',
                  {'broker': broker,
                   'transactions': transactions,
                   'total': total})
    
def byBondType(request, bondtype_id):
    bondtype = get_object_or_404(BondType, pk=bondtype_id)
    matching_bonds = Bond.objects.filter(bondtype=bondtype)

    common = get_common_data(request)
    
    transactions = Transaction.objects.filter(
        owner=common.investor,
        bond__in=matching_bonds,
        transactionDate__gte=common.from_date,
        transactionDate__lte=common.to_date)
    
    total = transactions_total(transactions)

    addAnnualizedRates(transactions)

    return render(request, 'reports/byBondType.html',
                  {'bondtype': bondtype,
                   'transactions': transactions,
                   'total': total})

def byBond(request, bond_id):
    bond = get_object_or_404(Bond, pk=bond_id)

    common = get_common_data(request)
    
    transactions = Transaction.objects.filter(
        owner=common.investor,
        bond=bond,
        transactionDate__gte=common.from_date,
        transactionDate__lte=common.to_date)
    
    total = transactions_total(transactions)

    addAnnualizedRates(transactions)

    return render(request, 'reports/byBond.html',
                  {'bond': bond,
                   'transactions': transactions,
                   'total': total})

def allTransactions(request):
    if not request.user.is_authenticated():
        return redirect('/admin/login/?next=/')
    
    common = get_common_data(request)

    transactions = Transaction.objects.filter(
        owner=common.investor,
        transactionDate__gte=common.from_date,
        transactionDate__lte=common.to_date)

    total = transactions_total(transactions)

    addAnnualizedRates(transactions)

    return render(request, 'reports/allTransactions.html',
                  {'transactions': transactions,
                   'total': total})
    
def changeDates(request):
    if request.method == "POST":
        fromDate = parseDate(request.POST['from'], DEFAULT_FROM_DATE)
        toDate = parseDate(request.POST['to'], DEFAULT_TO_DATE)

        # save parsed dates to session data
        request.session['fromDate'] = displayDate(fromDate)
        request.session['toDate'] = displayDate(toDate)
        
        if is_safe_url(request.POST['prevUrl']):
            return redirect(request.POST['prevUrl'])
    return redirect(reverse('reports:index'))

def resetDates(request):
    request.session['fromDate'] = displayDate(DEFAULT_FROM_DATE)
    request.session['toDate'] = displayDate(DEFAULT_TO_DATE)
    if is_safe_url(request.GET['prevUrl']):
        return redirect(request.GET['prevUrl'])
    return redirect(reverse('reports:index'))

# aggregate reports

def aggregateAll(request):
    common = get_common_data(request)
    
    transactions = Transaction.objects.filter(
        owner=common.investor,
        transactionDate__gte=common.from_date,
        transactionDate__lte=common.to_date)

    aggregates = aggregateTransactions(transactions)

    total = transactions_total(transactions)

    return render(request, 'reports/aggregateAll.html',
                  {'aggregates': aggregates, 'total': total})

def aggregateByBroker(request):
    common = get_common_data(request)

    brokers = Broker.objects.filter(client=common.investor)

    # want to return
    # brokerAggregate = [{'name': 'Itau', 'bonds': [{'name': 'LTN' ...

    brokersDict = defaultdict(BrokerBonds)

    for broker in brokers:
        transactions = Transaction.objects.filter(
            broker=broker,
            owner=common.investor,
            transactionDate__gte=common.from_date,
            transactionDate__lte=common.to_date)

        brokersDict[broker.name].name = broker.name
        brokersDict[broker.name].total = transactions_total(transactions)
        brokersDict[broker.name].bonds = aggregateTransactions(transactions)

    sortedBrokerNames = sorted(brokersDict)
    
    result = []
    
    for brokerName in sortedBrokerNames:
        result.append({'name': brokerName,
                       'total': brokersDict[brokerName].total,
                       'aggregates': brokersDict[brokerName].bonds})

    return render(request, 'reports/aggregateByBroker.html',
                  {'brokers': result})

def aggregateByBondType(request):
    common = get_common_data(request)

    bondtypes = BondType.objects.all()

    bondtypesDict = defaultdict(BondTypeBonds)

    for bondtype in bondtypes:
        transactions = Transaction.objects.filter(
            bond__bondtype=bondtype,
            owner=common.investor,
            transactionDate__gte=common.from_date,
            transactionDate__lte=common.to_date)

        bondtypesDict[bondtype.code].name = str(bondtype)
        bondtypesDict[bondtype.code].total = transactions_total(transactions)
        bondtypesDict[bondtype.code].bonds = aggregateTransactions(transactions)

    sortedBondtypeNames = sorted(bondtypesDict)
    
    result = []
    
    for bondtypeName in sortedBondtypeNames:
        result.append({'name': bondtypesDict[bondtypeName].name,
                       'total': bondtypesDict[bondtypeName].total,
                       'aggregates': bondtypesDict[bondtypeName].bonds})

    return render(request, 'reports/aggregateByBondType.html',
                  {'bondtypes': result})

reports/templates/reports/aggregateAll.html
{% extends 'reports/base.html' %}

{% block title %}All Transactions (Aggregate){% endblock %}

{% block content %}
<p>
    Aggregate by Bond
</p>

{% include "reports/aggregateList.html" %}

{% endblock %}

reports/templates/reports/aggregateByBondType.html
{% extends 'reports/base.html' %}

{% block title %}Aggregate by Broker{% endblock %}

{% block content %}
Aggregate by Type

{% for bondtype in bondtypes %}
<p>
    {{ bondtype.name }}
    <br><br>    
    {% include 'reports/aggregateListByBondType.html' %}
    
</p>
<hr>
{% endfor %}

{% endblock %}

reports/templates/reports/aggregateByBroker.html
{% extends 'reports/base.html' %}

{% block title %}Aggregate by Broker{% endblock %}

{% block content %}
Aggregate by Broker

{% for broker in brokers %}
<p>
    {{ broker.name }}
    
    {% include 'reports/aggregateListByBroker.html' %}
    
</p>
<hr>
{% endfor %}

{% endblock %}

reports/templates/reports/aggregateDebug.html
{% load humanize %}

{{ aggregates }}

{% for bond in aggregates %}
{{ bond }}
{% endfor %}

reports/templates/reports/aggregateList.html
{% load humanize %}

total <span class="transactionsTotal">{{ total|intcomma }}</span>

<table class="transactionsTable" id="transactionsTable">
    <thead>
        <tr>
            <th class="transactionsCell">Bond Type</th>
            <th class="transactionsCell">Maturity</th>
            <th class="transactionsCell">Mat. YMD</th>
            <th class="transactionsCell">Quantity</th>
            <th class="transactionsCell">Total Price</th>
            <th class="transactionsCell">Mkt. Price</th>
            <th class="transactionsCell">Unit Price</th>
            <th class="transactionsCell">Mkt. Date</th>
            <th class="transactionsCell">Sort. Price</th>
        </tr>
    </thead>
    
    {% for bond in aggregates %}
    <tr>
        <td class="transactionsCell">
            {% comment %} <a href="{% url 'reports:by-bond-type' aggregate.bond.bondtype.id %}">{{ bond.name }}</a> {% endcomment %}
            {{ bond.name }}
        </td>

        <td class="transactionsCell">
            <a href="{% url 'reports:by-bond' bond.id %}">
                {{ bond.maturity }}
            </a>
        </td>
        
        <td class="transactionsCell">
            {% comment %}
            <!-- <a href="{% url 'reports:by-bond' aggregate.bond.id %}">{{ aggregate.bond.maturity|date:'Y-m-d' }}</a> -->
            {% endcomment %}
            {{ bond.maturityYMD }}
        </td>
        
        <td class="transactionsCell">{{ bond.quantity|intcomma }}</td>
        <td class="transactionsCell">{{ bond.totalPrice|intcomma }}</td>

        <td class="transactionsCell">{{ bond.totalLatestPrice }}</td>
        <td class="transactionsCell">{{ bond.latestPrice }}</td>
        <td class="transactionsCell">{{ bond.latestPriceDate|date:'d/m/y' }}</td>
        <td class="transactionsCell">{{ bond.sortablePrice }}</td>
    </tr>
    {% endfor %}
</table>

<script src="/static/reports/tablesorter.js"></script>

reports/templates/reports/aggregateListByBondType.html
{% load humanize %}

total <span class="transactionsTotal">{{ bondtype.total|intcomma }}</span>

<table class="transactionsTable">
    <thead>
        <tr>
            <th class="transactionsCell">Bond Type</th>
            <th class="transactionsCell">Maturity</th>
            <th class="transactionsCell">Mat. YMD</th>
            <th class="transactionsCell">Quantity</th>
            <th class="transactionsCell">Total Price</th>
            <th class="transactionsCell">Mkt. Price</th>
            <th class="transactionsCell">Unit Price</th>
            <th class="transactionsCell">Mkt. Date</th>
            <th class="transactionsCell">Sort. Price</th>
        </tr>
    </thead>
    
    {% for bond in bondtype.aggregates %}
    <tr>
        <td class="transactionsCell">
            {% comment %} <a href="{% url 'reports:by-bond-type' aggregate.bond.bondtype.id %}">{{ bond.name }}</a> {% endcomment %}
            {{ bond.name }}
        </td>

        <td class="transactionsCell">
            {% comment %}
            <a href="{% url 'reports:by-bond' aggregate.bond.id %}">{{ aggregate.bond.maturity|date:'d/m/y' }}</a>
            {% endcomment %}
            {{ bond.maturity }}
        </td>
        
        <td class="transactionsCell">
            {% comment %}
            <!-- <a href="{% url 'reports:by-bond' aggregate.bond.id %}">{{ aggregate.bond.maturity|date:'Y-m-d' }}</a> -->
            {% endcomment %}
            {{ bond.maturityYMD }}
        </td>
        
        <td class="transactionsCell">{{ bond.quantity|intcomma }}</td>
        <td class="transactionsCell">{{ bond.totalPrice|intcomma }}</td>

        <td class="transactionsCell">{{ bond.totalLatestPrice }}</td>
        <td class="transactionsCell">{{ bond.latestPrice }}</td>
        <td class="transactionsCell">{{ bond.latestPriceDate|date:'d/m/y' }}</td>
        <td class="transactionsCell">{{ bond.sortablePrice }}</td>
    </tr>
    {% endfor %}
</table>

<script src="/static/reports/tablesorter.js"></script>

reports/templates/reports/aggregateListByBroker.html
{% load humanize %}

total <span class="transactionsTotal">{{ broker.total|intcomma }}</span>

<table class="transactionsTable" id="transactionsTable">
    <thead>
        <tr>
            <th class="transactionsCell">Bond Type</th>
            <th class="transactionsCell">Maturity</th>
            <th class="transactionsCell">Mat. YMD</th>
            <th class="transactionsCell">Quantity</th>
            <th class="transactionsCell">Total Price</th>
            <th class="transactionsCell">Mkt. Price</th>
            <th class="transactionsCell">Unit Price</th>
            <th class="transactionsCell">Mkt. Date</th>
            <th class="transactionsCell">Sort. Price</th>
        </tr>
    </thead>
    
    {% for bond in broker.aggregates %}
    <tr>
        <td class="transactionsCell">
            {% comment %} <a href="{% url 'reports:by-bond-type' aggregate.bond.bondtype.id %}">{{ bond.name }}</a> {% endcomment %}
            {{ bond.name }}
        </td>

        <td class="transactionsCell">
            {% comment %}
            <a href="{% url 'reports:by-bond' aggregate.bond.id %}">{{ aggregate.bond.maturity|date:'d/m/y' }}</a>
            {% endcomment %}
            {{ bond.maturity }}
        </td>
        
        <td class="transactionsCell">
            {% comment %}
            <!-- <a href="{% url 'reports:by-bond' aggregate.bond.id %}">{{ aggregate.bond.maturity|date:'Y-m-d' }}</a> -->
            {% endcomment %}
            {{ bond.maturityYMD }}
        </td>
        
        <td class="transactionsCell">{{ bond.quantity|intcomma }}</td>
        <td class="transactionsCell">{{ bond.totalPrice|intcomma }}</td>

        <td class="transactionsCell">{{ bond.totalLatestPrice }}</td>
        <td class="transactionsCell">{{ bond.latestPrice }}</td>
        <td class="transactionsCell">{{ bond.latestPriceDate|date:'d/m/y' }}</td>

        <td class="transactionsCell">{{ bond.sortablePrice }}</td>
    </tr>
    {% endfor %}
</table>

<script src="/static/reports/tablesorter.js"></script>

reports/templates/reports/allTransactions.html
{% extends 'reports/base.html' %}

{% block title %}All Transactions{% endblock %}

{% block content %}
All Transactions
<br><br>
<span style="color: red;">Backup:</span> Copy the db.sqlite3 file

{% include "reports/transactionList.html" %}

{% endblock %}

reports/templates/reports/bonds.html
{% extends "reports/base.html" %}

{% block title %}Brokers{% endblock %}

{% block content %}

<table>
{% for b in bonds %}

    <tr><td><a href="/reports/by-bond/{{ b.id }}">{{ b }}</a></td></tr>

{% endfor %}
</table>

{% endblock %}

reports/templates/reports/bondtypes.html
{% extends "reports/base.html" %}

{% block title %}Brokers{% endblock %}

{% block content %}

<table>
{% for bt in bondtypes %}

    <tr><td><a href="/reports/by-bondtype/{{ bt.id }}">{{ bt }}</a></td></tr>

{% endfor %}
</table>

{% endblock %}

reports/templates/reports/brokers.html
{% extends "reports/base.html" %}

{% block title %}Brokers{% endblock %}

{% block content %}

<table>
{% for broker in brokers %}

    <tr><td><a href="/reports/by-broker/{{ broker.id }}">{{ broker }}</a></td></tr>

{% endfor %}
</table>

{% endblock %}

reports/templates/reports/byBondType.html
{% extends 'reports/base.html' %}

{% block title %}Bond Type - {{ bondtype }}{% endblock %}

{% block content %}
{{ bondtype }}

{% include "reports/transactionList.html" %}

{% endblock %}

reports/templates/reports/byBroker.html
{% extends 'reports/base.html' %}

{% block title %}Broker - {{ broker.name }}{% endblock %}

{% block content %}
{{ broker.name }}

{% include "reports/transactionList.html" %}

{% endblock %}

reports/templates/reports/index.html
{% extends "reports/base.html" %}

{% block title %}Index{% endblock %}

{% block content %}

<h3>Reports</h3>

<table>
{% for broker in brokers %}

    <tr><td><a href="by-broker/{{ broker.id }}">{{ broker }}</a></td></tr>

{% endfor %}
</table>

{% endblock %}